### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by zhrm0110** [wong2/xiaohuangji#16]
运行python rqworker.py遇到AttributeError: 'NoneType' object has no attribute 'group'，怎么办啊？
完整日志：
login successfully
Traceback (most recent call last):
  File "rqworker.py", line 13, in <module>
    from controller import bots, getNotiData, self_match_pattern
  File "/home/vagrant/git/xiaohuangji/controller.py", line 83, in <module>
    bots = getBots(accounts)
  File "/home/vagrant/git/xiaohuangji/controller.py", line 80, in getBots
    bot.login(account[0], account[1])
  File "/home/vagrant/git/xiaohuangji/renren.py", line 103, in login
    self.getToken(r.text)
  File "/home/vagrant/git/xiaohuangji/renren.py", line 133, in getToken
    'requestToken': result.group(1),
AttributeError: 'NoneType' object has no attribute 'group'
还有，怎么样才能进入教学模式呢？

**Comment by wong2** [comment]
@zhrm0110 这个项目已经没有在维护了
